`define GOWIN_GPIO_SUPPORT
`define GOWIN_UART0_SUPPORT
`define GOWIN_UART1_SUPPORT
`define GOWIN_RTC_SUPPORT
`define GOWIN_I2C_SUPPORT
`define I2C_IOBUF_EN
`define GOWIN_SPI_SUPPORT
`define NUM_BRAMS_2
