-d C:\kitahard\Tang_Nano_4K\led_test\impl\gwsynthesis\led_test.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\kitahard\Tang_Nano_4K\led_test\src\led_test.cst
-cfg C:\kitahard\Tang_Nano_4K\led_test\impl\pnr\device.cfg
-gao C:\kitahard\Tang_Nano_4K\led_test\impl\gao\gao.v
-gao_crc 1011101100110100
-bit
-tr
-ph
-timing
-cst_error
